# Tutorial

Symbolic sequences can arise in very different contexts from abstract symbolic dynamics, to encoding of behavioral sequences, through information theory, discrete Markov processes, etc. Here we take an applied perspective to stay in the spirit of large audience tutorial.

## The `Sequence` objects

The basic objects of `scyseq` are symbolic _sequences_ (instances of the `Sequence` class) which are are ordered sequences of _symbols_ (instances of the `Symbol` class) taken from a finite set of symbols called an _alphabet_ (instance of the `Alphabet` class). Alphabets can typically be a set of integers but in some contexts, they need to be associated with some meaning. Thus, symbolic sequences have two representations one according to integers and the other according strings.

### Example

Let's take the example of the observation of a person waiting for her plane at the airport. We can imagine to encode her behavior as `sitting` or `standing`. 

In [8]:
import scyseq as sq

st = sq.Symbol('sitting')
print(st) # a single symbol does not have integer representation
sd = sq.Symbol('standing')
behav = sq.Alphabet([st,sd]) # symbols in an alphabet get integer representation
print(behav)

(- | sitting)
((0 | sitting), (1 | standing))
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [9]:
bseq = sq.Sequence([0,1,0,1,1], behav)
# FIXME: decide the representation...
print(bseq)

[0 1 0 1 1] 1 2
[0 1 0 1 1]


In [10]:
sq.Alphabet(3)

Alphabet(Symbol(0 | 0), Symbol(1 | 1), Symbol(2 | 2))

In [6]:
import numpy as np

rr = np.random.choice(range(2), 20)
sq.Sequence(rr, behav)

[1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0] 1 2


Sequence: [1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0]
Alphabet(Symbol(0 | sitting), Symbol(1 | standing))
N = 20 ; k = 2